spring.application.name=estoque-backend
server.port=8080

spring.datasource.url=jdbc:h2:mem:estoque_db;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# flyway vai criar as tabelas, então deixo o Hibernate só validar
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
