CREATE TABLE produto (
    codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(120) NOT NULL,
    tipo_produto VARCHAR(30) NOT NULL,
    valor_no_fornecedor DECIMAL(14,2) NOT NULL,
    estoque INT NOT NULL
);

CREATE INDEX idx_produto_tipo ON produto (tipo_produto);


CREATE TABLE movimento_estoque (
    codigo_movimentacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_produto BIGINT NOT NULL,
    tipo_movimentacao VARCHAR(30) NOT NULL,
    valor_venda DECIMAL(14,2),
    data_venda TIMESTAMP,
    qtd_movimentada INT NOT NULL,

    CONSTRAINT fk_movimento_produto
        FOREIGN KEY (codigo_produto)
        REFERENCES produto(codigo)
);

CREATE INDEX idx_movimento_produto ON movimento_estoque (codigo_produto);
CREATE INDEX idx_movimento_tipo ON movimento_estoque (tipo_movimentacao);
CREATE INDEX idx_movimento_data ON movimento_estoque (data_venda);